### ISSUE TITLE
Libgdx not working in 2020.0.2-PREVIEW

### ISSUE THREAD

**Issue by klaushauschild1984** [Hexworks/zircon#305]
**Describe the bug**
When I try to create a LibGDX based application in zircon-2020.0.2-PREVIEW it fails with
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/hexworks/zircon/api/application/RenderData
	at org.hexworks.zircon.internal.application.LibgdxApplication.<init>(LibgdxApplication.kt:24)
	at org.hexworks.zircon.internal.application.LibgdxApplication.<init>(LibgdxApplication.kt:15)
	at org.hexworks.zircon.internal.application.LibgdxGame.<init>(LibgdxGame.kt:24)
	at org.hexworks.zircon.internal.application.LibgdxGame.<init>(LibgdxGame.kt:16)
	at org.hexworks.zircon.internal.application.LibgdxGame$Companion.build(LibgdxGame.kt:64)
	at org.hexworks.zircon.api.LibgdxApplications.makeLibgdxGame(LibgdxApplications.kt:98)
	at org.hexworks.zircon.api.LibgdxApplications.startTileGrid(LibgdxApplications.kt:64)
	at org.hexworks.zircon.api.LibgdxApplications.startTileGrid$default(LibgdxApplications.kt:61)
	at org.hexworks.zircon.api.LibgdxApplications.startTileGrid(LibgdxApplications.kt)
	at com.nintendostuff.galaxies.rl.Main2.main(Main2.java:17)
Caused by: java.lang.ClassNotFoundException: org.hexworks.zircon.api.application.RenderData
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more
```

Sample for reproduction:
```
import org.hexworks.zircon.api.CP437TilesetResources;
import org.hexworks.zircon.api.LibgdxApplications;
import org.hexworks.zircon.api.application.AppConfig;
import org.hexworks.zircon.api.data.Size;

public class Main2 {

    public static void main(final String[] args) {
        final AppConfig appConfig = AppConfig.newBuilder()
            .withSize(Size.create(90, 50))
            .withDefaultTileset(CP437TilesetResources.rexPaint16x16())
            .withFpsLimit(60)
            .withDebugMode(false)
            .build();
        LibgdxApplications.startTileGrid(appConfig);
    }
}
```

**Comment by adam-arold** [comment]
I think this is a change external to Zircon. Something changed in the LibGDX ecosystem since we didn't change any underlying code. I'm gonna take a look if I can do something though.

**Comment by klaushauschild1984** [comment]
I didn't do any further investigation like downgrading libGDX version or so, but I can do.

**Comment by klaushauschild1984** [comment]
But the missing class is from `org.hexworks.zircon.api.application`. How is this dependent to LibGDX?

**Comment by klaushauschild1984** [comment]
I am an idiot!
This is totally my fault. I combined `zircon.core-jvm-2020.0.2-PREVIEW` with `zircon.jvm.libgdx-2020.1.1-PREVIEW`. No further investigation needed. Everything working fine besides missing features, but thats an other issue.
